### ISSUE TITLE
Error running app on Android

### ISSUE THREAD

**Issue by Kryptonit3-zz** [hollyschinsky/PushNotificationSample#10]
This is what I get when I run the app, then click register. 
Yes I have changed the GCM ID and URLs in controller.js

```
03-08 20:05:26.618    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:26.625    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:26.698    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:26.698    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:26.711    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:26.716    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:26.762    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:26.762    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:26.771    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:26.775    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:26.815    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:26.815    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:26.826    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:26.832    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:26.856    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:26.857    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:26.866    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:26.882    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.091    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.091    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.108    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.117    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.173    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.173    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.181    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.185    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.241    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.241    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.249    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.253    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.298    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.298    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.309    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.313    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.387    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.388    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.398    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.404    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.448    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.448    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.455    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.461    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.504    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.504    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.513    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.517    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.572    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.572    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.582    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.586    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.638    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.638    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.645    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.652    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.692    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.692    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.707    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.713    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.763    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.763    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.767    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.774    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.793    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.793    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.802    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.808    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.827    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.827    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.837    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.842    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.853    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.854    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.857    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.870    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.880    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.880    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.887    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.893    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.911    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.911    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.920    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.924    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.935    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.935    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.945    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000b44
03-08 20:05:27.950    2303-2303/co.gandc.notify D/CordovaActivity﹕ onMessage(spinner,stop)
03-08 20:05:27.953    2303-2373/co.gandc.notify E/eglCodecCommon﹕ glUtilsParamSize: unknow param 0x00000bd0
03-08 20:05:27.972    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:27.972    2303-2373/co.gandc.notify E/eglCodecCommon﹕ **** ERROR unknown type 0x0 (glSizeof,72)
03-08 20:05:45.001    2303-2303/co.gandc.notify D/CordovaLog﹕ file:///android_asset/www/lib/ionic/js/ionic.bundle.js: Line 17696 : TypeError: Cannot read property 'pushNotification' of undefined
            at Object.register (file:///android_asset/www/lib/ng-cordova.js:4484:36)
            at Scope.$scope.register (file:///android_asset/www/js/controllers.js:33:22)
            at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:18471:21
            at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:43026:9
            at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20326:28)
            at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20424:23)
            at HTMLButtonElement.<anonymous> (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:43025:13)
            at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:10478:10
            at forEach (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:7950:18)
            at HTMLButtonElement.eventHandler (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:10477:5)
03-08 20:05:45.001    2303-2303/co.gandc.notify I/chromium﹕ [INFO:CONSOLE(17696)] "TypeError: Cannot read property 'pushNotification' of undefined
            at Object.register (file:///android_asset/www/lib/ng-cordova.js:4484:36)
            at Scope.$scope.register (file:///android_asset/www/js/controllers.js:33:22)
            at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:18471:21
            at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:43026:9
            at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20326:28)
            at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20424:23)
            at HTMLButtonElement.<anonymous> (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:43025:13)
            at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:10478:10
            at forEach (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:7950:18)
            at HTMLButtonElement.eventHandler (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:10477:5)", source: file:///android_asset/www/lib/ionic/js/ionic.bundle.js (17696)
```

**Comment by Kryptonit3-zz** [comment]
forgot to import push plugin
